# Generated by Django 3.0.1 on 2020-01-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_num', models.IntegerField(verbose_name='participant number')),
                ('participant_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
