# Generated by Django 3.0.1 on 2020-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0002_auto_20200110_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='deepfake_obfus',
            field=models.ImageField(blank=True, upload_to='images/deepfake'),
        ),
    ]
