# Generated by Django 3.0.1 on 2020-01-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0004_participant_blurred_obfus'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='pixelated_obfus',
            field=models.ImageField(blank=True, upload_to='images/blurred'),
        ),
    ]
