# Generated by Django 3.0.1 on 2020-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0005_participant_pixelated_obfus'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='masked_obfus',
            field=models.ImageField(blank=True, upload_to='images/blurred'),
        ),
    ]
