# Generated by Django 3.0.1 on 2020-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0006_participant_masked_obfus'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
