# Generated by Django 3.0.1 on 2020-01-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0007_auto_20200126_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='participant',
            name='skin_tone',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='', max_length=64),
        ),
    ]
