# Generated by Django 3.0.1 on 2020-01-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0008_auto_20200126_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='avatar_obfus',
            field=models.ImageField(blank=True, upload_to='images/avatar'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='masked_obfus',
            field=models.ImageField(blank=True, upload_to='images/masked'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pixelated_obfus',
            field=models.ImageField(blank=True, upload_to='images/pixelated'),
        ),
    ]
