# Generated by Django 3.0.1 on 2020-01-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfus', '0010_participant_not_participant_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bystander_avatar_obfus',
            field=models.ImageField(blank=True, upload_to='images/avatar'),
        ),
        migrations.AddField(
            model_name='participant',
            name='bystander_blurred_obfus',
            field=models.ImageField(blank=True, upload_to='images/blurred'),
        ),
        migrations.AddField(
            model_name='participant',
            name='bystander_deepfake_obfus',
            field=models.ImageField(blank=True, upload_to='images/deepfake'),
        ),
        migrations.AddField(
            model_name='participant',
            name='bystander_masked_obfus',
            field=models.ImageField(blank=True, upload_to='images/masked'),
        ),
        migrations.AddField(
            model_name='participant',
            name='bystander_pixelated_obfus',
            field=models.ImageField(blank=True, upload_to='images/pixelated'),
        ),
        migrations.AddField(
            model_name='participant',
            name='not_participant_pic_left',
            field=models.ImageField(blank=True, upload_to='images/cropped/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='not_participant_pic_right',
            field=models.ImageField(blank=True, upload_to='images/cropped/'),
        ),
    ]
